### ISSUE TITLE
Possibility to copy to 'latest' tag

### ISSUE THREAD

**Issue by Askelkana** [iVantage/grunt-svn-tag#12]
It would be nice if the tagged version would get (optionally) copied to a 'latest' tag at the same time. This would mean client projects could get the latest version of a tagged release without having to update the configuration all the time.

**Comment by jtrussell** [comment]
That's an interesting idea. How would you feel about:

- Making this a multitask
- Add an "overwrite" option

If it were a multitask we could copy both to a semver tag and something like "latest" in one pass. If my understanding of copying in subversion is right we'd need to first delete an existing "latest" tag before copying onto it, otherwise you'd get something like "latest/latest".

**Comment by Askelkana** [comment]
You might want to check out my plugin [grunt-svn-custom-tag](https://github.com/Askelkana/grunt-svn-custom-tag), which provides a boolean option to write to latest or not.

So, with the multitask approach, one would simply have to provide a 'latest' task with a static version label. And the overwrite option would simply delete (if true) any existing tag folder, whatever it was called, before writing. I think I've understood you. That's a workable solution.

**Comment by jtrussell** [comment]
Cool, I prefer the generic multitask - with an option to override - over assuming "latest". If that works for you I'd be open to a PR :).

**Comment by Askelkana** [comment]
Hi,

I've forked the code and made the basic changes necessary. However, I'm having trouble finalising this, as there seems to me to be a bug in the code. The issue has arisen because I'm having to test the module using ``projectRoot``, since the default determination of the project's svn url has to be overridden.

First off, ``projectRoot`` is completely ignored when performing the ``svnInfo.sync()`` check. At least I think it  should be passed. So I added that to make progress. Next obstacle: the info returned by the command-line ``svn info`` differs when passing the working copy path and passing the repository url via ``projectRoot`` (which is really what is wanted). In the latter form, the ``'/trunk'`` ending is missing. So, an exception is thrown saying as much, and the task fails. If one includes ``'/trunk'`` in ``projectRoot`` then it is duplicated when determining ``fromURL``.

Do you follow? Anyway, I cannot really finalise this issue until these others are resolved, not without a lot of bothersome hassle.

**Comment by jtrussell** [comment]
I'm not sure I completely follow you. Would you mind posting the relevant parts of your gruntfile?

**Comment by Askelkana** [comment]
The Gruntfile isn't the thing, since the only relevant part is the projectRoot option. Instead, I'll try and break it down further.

According to the README, projectRoot takes precedence over svnInfo. And yet the code uses svnInfo anyway to determine the source folder (fromPath). It seems inconsistent.

Would you agree that the projectRoot option should be passed into the svnInfo.sync() call on line 87? If it isn't, then why is it used at all? Without it, svnInfo.sync checks against the cwd, which may not be what is wanted.

To be honest, I'm confused and it's quite unclear to me what the correct logic should be. At least to me it seems that the current incarnation in incomplete or erroneous. Have you tested the usage of projectRoot?

**Comment by jtrussell** [comment]
> The Gruntfile isn't the thing, since the only relevant part is the projectRoot option. Instead, I'll try and break it down further.

Ok, then what are you passing as a project root (I suspect your are not providing a valid project root)? Also, what does `svn info` output for you? Can you provide the output of `grunt svn_tag --dry-run`?

> According to the README, projectRoot takes precedence over svnInfo. And yet the code uses svnInfo anyway to determine the source folder (fromPath). It seems inconsistent.

Are we talking about the same project root? https://svn.apache.org/repos/asf/subversion/trunk/doc/user/svn-best-practices.html (search for "project root").

The README says `projectRoot` is the parent folder of `tags`, i.e.:

```
<projectRoot>
+-- trunk
+-- branches
|    +-- featureBranch0
|    +-- featureBranch1
+-- tags
|    +-- v1.0.0
|    +-- v1.0.1
```

The project root directory lives above and location you will want to create a tag of.

> Would you agree that the projectRoot option should be passed into the svnInfo.sync() call on line 87? If it isn't, then why is it used at all? Without it, svnInfo.sync checks against the cwd, which may not be what is wanted.

I may be mistaken but I don't believe there's much use in passing the `projectRoot` to `svnInfo.sync()` here.

The business of determining the `fromPath` (lines [85 to 108](https://github.com/iVantage/grunt-svn-tag/blob/master/tasks/svn_tag.js#L85-L108)) is so we can figure out which branch to create a tag for, i.e. which path to copy from. By design this will always be the url corresponding to your working copy.

Essentially, we want to:

```
svn copy <fromPath> <projectRoot>/tags/<tagName>
```

See [line 119](https://github.com/iVantage/grunt-svn-tag/blob/master/tasks/svn_tag.js#L119).

> To be honest, I'm confused and it's quite unclear to me what the correct logic should be. At least to me it seems that the current incarnation in incomplete or erroneous. Have you tested the usage of projectRoot?

I have, and it seems to behave as expected. Would you mind providing the relevant part of your Gruntfile and the output of those commands?

**Comment by Askelkana** [comment]
Sorry I've not responded sooner.

The problem, as I see it is that you ignore projectRoot when determining whether on trunk or a branch. You use svnInfo to determine this, which is fine, but it uses the grunt job's cwd. This is, IMO, an unwarranted assumption, and in making it, you render projectRoot virtually useless. This is why I assumed you would want to use projectRoot when calling svnInfo.

According to the README:

> Project roots are determined by checking the following in order:
>    The task options for a 'projectRoot' property
>    Your package.json file for repository.url (if respository.type === 'svn')
>    The url returned by svn info

Steps 1 and 2 hold. But step 3 is always taken regardless. This is the error in the logic as I see it.

**Comment by jtrussell** [comment]
Ok, as I said we're essentially trying to build this command:

```
svn copy <fromPath> <projectRoot>/tags/<tagName>
```

How would you propose we get the full `<fromPath>` without a call to svnInfo?

**Comment by Askelkana** [comment]
I'm not saying svnInfo should not be called. My issue (or what I'm failing to grasp) is that the current call is completely detached from <projectRoot>, which seems to me to be an error. Why provide the option of <projectRoot> as a destination but not account for it being a source also? i.e. why call svnInfo on the cwd of the grunt job? Surely, if one is copying to a /tags folder, then it is associated with the /trunk or /branches folder under <projectRoot>? Or at least that is a reasonable (typical) scenario. i.e. we are wanting:

    svn copy <projectRoot>/[trunk|branches/X] <projectRoot>/tags/<tagName>

Or have I missed the plot completely?

**Comment by jtrussell** [comment]
Isn't that exactly what we're doing though? When a project root is given we just use svnInfo to determine [trunk|branches/X].

**Comment by Askelkana** [comment]
An empty call to svnInfo is based on the assumption that the grunt job resides in the working copy. That's reasonable enough, I suppose. But then why the need for &lt;projectRoot>? If &lt;projectRoot> _is_ required, then using the working copy is hardly appropriate.

In other words:

    svn copy <path_determined_from_working_copy> <projectRoot>/tags/<tagName>

is not the same as

    svn copy <projectRoot>/[trunk|branches/X] <projectRoot>/tags/<tagName>

where &lt;projectRoot> is anything different from the root supplied by svnInfo.

**Comment by jtrussell** [comment]
But those should be the same if `<projectRoot>` is set appropriately, `<path_determined_from_working_copy>` takes the given `<projectRoot>` and appends `/[trunk|branches/X]` as determined by the working copy's svn path. We don't get `<path_determined_from_working_copy>` in its entirety from svnInfo, just the `[trunk|branches/X]` bit:

https://github.com/iVantage/grunt-svn-tag/blob/master/tasks/svn_tag.js#L111

We *do* assume the path corresponding to your working copy is the thing you want to tag (it's called out in the overview section of our README). We also assume your gruntfile lives at the top of your module/app next to the package.json file, we don't mention this explicitly but it seems a fair assumption based on the [grunt docs](http://gruntjs.com/getting-started#package.json).

The project root option was added to support folks who keep multiple projects in the same repo (in a time when [svn-project-root](https://github.com/jtrussell/node-svn-project-root) didn't account for this case). It was essentially a concession to the fact that (at the time) we weren't reliably determining the project root for all svn projects that were following best practices. In these cases the repository root provided by svn-info was is not the actual root of the project, though it was the root of the repository.

At this point - as far as we know - the svn-project-root module is smarter and the project root option here should at worst be redundant.

I'm still unclear as to what path you would suggest passing to svnInfo. I think if we had a concrete example it would really clear things up. Would you mind providing the info I asked for above?

- What is the output of `svn info` in the folder containing your gruntfile?
- What are you providing as a project root?
- What is outcome you are expecting?

**Comment by Askelkana** [comment]
Ok, now that I understand the assumptions upon which the logic works, it was easy to proceed and finalise this change. My difficulties stemmed from lacking this insight. Sorry for the hassle.

I've now created a pull request (#13) for you to look at. The README documentation has *not* been updated.

**Comment by Askelkana** [comment]
Perhaps this issue can be closed now...
