### ISSUE TITLE
The plugin does not tag the working copy

### ISSUE THREAD

**Issue by luje** [iVantage/grunt-svn-tag#15]
So.. we are trying to use this plugin to tag the working copy that is checked out by jenkins in out CI job. The problem that we are having is that we have cases when we release a certain revision of trunk and not the top of trunk. This plugin tags the top of trunk or a branch (meaning the latest revision) and not the local working copy.

I suggest removing the part of the code that determines from svn-info what is the local path (either trunk or branch) and just tag the local copy. This way you would be able to tag any revision of any branch (or trunk for that matter) and you would delegate this handling the the part of the build that does the checkout. From my experience, that is also the way that maven release plugin does it.

The svn command should be something along the lines of: "svn cp . remote_tag_url" or at least take a revision parameter

**Comment by jtrussell** [comment]
Good suggestion, actually I believe this was how the plugin worked long ago before we moved it to GitHub. I don't think we'll change the default behavior but adding an option for the path to tag would be fine. Feel free to send a PR.
