### ISSUE TITLE
Overwrite option not used when tagging twice on the same repo

### ISSUE THREAD

**Issue by splanard** [iVantage/grunt-svn-tag#16]
Hi,
If you use svn_tag grunt task twice on the same project, with the same version, without specifying `overwrite` option to `true`, the scond tag will be performed _inside_ the first one.
See below a practical example.

This is my trunk repo : 
`http://svn/repo/path/my-project/trunk`.
Let's say the current version is 1.0.0.

The first time I run `svn_tag`, this directory is created, with all the project files inside :
`http://svn/repo/path/my-project/tags/1.0.0`
Great.

Now, the second time I run `svn_tag` (the first one was a mistake or I forgot to bump my version or 2 devs do not communicate enough, etc.), here is what I obtain :
`http://svn/repo/path/my-project/tags/1.0.0/trunk`

This is a known behaviour of `svn copy`. See http://stackoverflow.com/questions/25410934/copy-twice-causes-branch-inside-a-branch-instead-of-error, among many other similar posts.

But since your plugin provides an option `overwrite`, it should check the existence of the tag before running the command in the case the option value is `false`.
I'm working on a pull request to fix this.

**Comment by jtrussell** [comment]
Thanks for the PR!
